"""initial schema

Revision ID: 4e866e25e879
Revises: 
Create Date: 2026-09-10 17:28:44.162471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e866e25e879'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_events_event_type'), 'journey_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_journey_events_session_id'), 'journey_events', ['session_id'], unique=False)
    op.create_table('journey_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('preferences_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journey_sessions')
    op.drop_index(op.f('ix_journey_events_session_id'), table_name='journey_events')
    op.drop_index(op.f('ix_journey_events_event_type'), table_name='journey_events')
    op.drop_table('journey_events')
    # ### end Alembic commands ###
